version: 0.2

env:
  variables:
    ECR_REGISTRY: 255748959698.dkr.ecr.us-east-1.amazonaws.com
    ECR_REPO: luzia

phases:
  pre_build:
    commands:
      - echo Fazendo login no ECR...
      - aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY
      - REPOSITORY_URI=$ECR_REGISTRY/$ECR_REPO
      - IMAGE_TAG="${CODEBUILD_WEBHOOK_TRIGGER#tag/}"
  build:
    commands:
      - echo Build iniciado em `date`
      - echo Gerando imagem da BIA...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build finalizado com sucesso em `date`
      - echo Fazendo push da imagem para o ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Gerando artefato da imagem para o ECS
      - printf '[{"name":"luzia","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
